### ISSUE TITLE
how to setup?

### ISSUE THREAD

**Issue by molelightn** [scheidtdav/kostal-piko-80-ba#1]
Hi there,

first thank you for your work on this project. I have a couple of questions as i don't get the Piko BA version to work.

I have installed the kostal integrations from gieljnssns which is working fine on 6 different Kostal Piko Inverters. But there is one more, a Piko BA 10.1 inverter which i can't get to work.

If i use platform: kostal_piko , it is unknown from HA, did gieljnssns changed the platform name from kostal_piko to kostal only? 

Further i do not understand how the authentication is made in your version for the Piko BA inverter.

There is no such username or password, i have also tried with following as host:

http://pvserver:<YOUR_PASSWORD>@<YOUR_INVERTER_IP>/index.fhtml

Also not working. I would appreciate if you could give me a hint or any reply to get the last of this inverters into HA.

Thank you in advance.

br Christoph

**Comment by scheidtdav** [comment]
Hi @molelightn !

Sorry my readme still lacks a bit of detail. This integration is supposed to be published to [HACS](hacs.xyz) but I haven't found the time to refactor a little bit and to finally publish it.
(Note to self: Thinking about it, I should actually open a merge request to the original kostal integration)

However it is working nicely in my test setup with a PIKO 8.0 BA for quite some time now.
It was me who changed the integration name, if I remember correctly, to prevent name conflicts with the kostal integration.

As far as I understand, there are several versions of the User Interface of the Piko inverters and therefore also the APIs. If your PIKO BA 10.1 has e.g. `index.fhtml` in its URL, this integration will likely not work.
Could you check your UI and FW version in your inverters web interface?
The PIKO 8.0. BA I'm using is running UI version 06.41 and FW version 02.30.

**Comment by molelightn** [comment]
Hi scheidtdav,

we upgraded BA inverter to UI version 6.41 but still had no luck with the integration.

As Kostal cancled some functions for batteries in the higher UI version the owner from the BA inverter decided to go back to the previous firmware.

Anyway thanks for your help, i guess we have to find another way.

br mole

**Comment by scheidtdav** [comment]
Bummer! I am not sure how much the UI versions differ between different inverters.
There might be still some differences that I am not aware of. It is hard to develop if you only have access to a single inverter and you have to reverse engineer the API ;-) 

Anyways, if you have to revert back due to some battery functionality, this integration cannot help, I guess.

I hope you can find another way :smile: 

Cheers!
